import Head from 'next/head'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div className='bg-red-500'>
      <Head>
        <title>Biya</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="positive">
        <Hero />
      </main>
    </div>
  )
}